---
info:
  icon: symbol:cloud.sun.fill
  name: WeatherAI
  enabled: true
  description: WeatherAI is an extension for asking AI about the weather.
actions:
  - meta:
      title: WeatherAI
      icon: symbol:cloud.sun.fill
      identifier: selected.aiweather
      after: ""
    gpt:
      prompt: "{selected.text}"
      tool:
        name: get_current_weather
        description: Get the current weather in a given location.
        parameters: '{"type":"object","properties":{"location":{"type":"string","description":"The city, e.g. SanFrancisco, 杭州"}},"required":["location"]}'
        command: ["./run.sh"]
