info:
  icon: square us
  name: ParseUnixTimeStamp
  description: UnixTimestamp is an extension used to convert Unix timestamps into dates.
actions:
  - meta:
      title: ParseUnixTimeStamp
      icon: square us
      identifier: selected.parse_uts
      after: "show"
      regex: "[0-9]+"
    runCommand:
      command:
        - /bin/zsh
        - parse.sh
