info:
  icon: square AC
  name: Auto Correct
  type: url
  description: improve copywriting, correct spaces, words, and punctuations between CJK (Chinese, Japanese, Korean).
actions:
  - meta:
      title: Auto Correct
      icon: square AC
      identifier: selected.autocorrent
      after: "paste"
    runCommand:
      command:
        - run.sh
