info:
  icon: "symbol:textformat"
  name: XcodeFormat
actions:
  - meta:
      title: XcodeFormat
      icon: "symbol:textformat"
      identifier: selected.xcode.format
      after: ""
    keycombo:
      keycombo: "ctr i"
